CREATE DATABASE IF NOT EXISTS LO54;

USE LO54;

CREATE TABLE IF NOT EXISTS LOCATION (
    id INT NOT NULL AUTO_INCREMENT,
    location VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS COURSE (
    code CHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(code)
);

CREATE TABLE IF NOT EXISTS COURSE_SESSION (
    id INT NOT NULL AUTO_INCREMENT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    max INT,
    course_code CHAR(20) NOT NULL,
    location_id INTEGER NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (course_code) REFERENCES COURSE(code),
    FOREIGN KEY (location_id) REFERENCES LOCATION(id)
);

CREATE TABLE IF NOT EXISTS CLIENT (
    id INT NOT NULL AUTO_INCREMENT,
    lastname VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    course_session_id INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (course_session_id) REFERENCES COURSE_SESSION(id)
);