# Use root/root as user/password credentials
version: '3.1'

services:

  db:
    build: .
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:4.6.3
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data:
